seed: 42

data:
  train_size: 10_000
  val_size: 32
  sample_len: 600
  spiral_freq_range: [1, 2.5]
  spiral_size_range: [5, 10]
  n_spiral_range: [300, 500]
  n_routs_range: [100, 200]
  start_point_range: 30
  noise_level: 0
  batch_size: 4
  num_workers: 4

arch:
  type: "MLP"
  kwargs:
    in_size: 1200

optim:
  optim_type: 'SGD'
  lr: 1.0e-4

train:
  max_epochs: 500
  overfit_batches: 1
  log_every_n_steps: 1

experiment_name: "overfit test"